### ISSUE TITLE
Should not require MySQL or PG gems

### ISSUE THREAD

**Issue by jarrett** [pdeffendol/spatial_adapter#10]
Most of us will be using either MySQL or PG, but not both. I happen to use MySQL. But spatial_adapter wants me to have the PG gem installed. It raises if I don't.

Installing an unneeded MySQL or PG gem is a huge hassle just to make this gem happy. Both require compiling C against installed libraries. If you don't happen to have the exact flavor of MySQL or PG library that the gem requires, you're in for a long night.

I was able to patch this for my own purposes by commenting out `require 'spatial_adapter/adapters/postgis'` in `lib/spatial_adapter.rb`. I realize, of course, that that's not a workable solution for you.

I think the gem needs to be configurable so that it only requires the database adapter that you're actually going to use.

What have other people been doing? I'm surprised this issue hasn't been raised before. It seems like it would affect a lot of people. (I doubt that most people have both PG and MySQL gems installed.)

**Comment by pdeffendol** [comment]
Interestingly, the MySQL adapter in ActiveRecord does not attempt to require the mysql gem until a connection is requested.  On the other hand, as soon as the postgres adapter file is require'd, it attempts to load the "pg" gem.  This is why spatial_adapter will not complain about the lack of a mysql gem if you are only using PostgreSQL.  The opposite is not true, as indicated by this ticket.

I can't patch the PostgreSQL adapter unless the file from ActiveRecord is require'd.  The only solution here that I can find is to submit a patch to ActiveRecord that defers the require_library_or_gem call until a connection is requested.  I'll work on it.

**Comment by gonzojive** [comment]
I would appreciate this as well :)

**Comment by pdeffendol** [comment]
I spent a couple hours on this today with minor success, but nothing commit ready.

**Comment by pdeffendol** [comment]
Here's my current idea, but no time to try it yet:
1. Don't automatically load all the adapters.  In "typical" (non-Rails) Ruby coding, you would load the gem and then manually "require" the adapter you want, e.g. "require spatial_adapter/postgresql"
2.  When using as a Rails plugin, check for the currently used database, and automatically include the appropriate adapter if it exists.

Yeah, this is close to the "old" functionality of spatial_adapter, but aside from splitting this into multiple gems/plugins for each database, I'm not sure what to do.

**Comment by pdeffendol** [comment]
I've refactored a little, and bumped the gem version to 1.0.0 to reflect the different in usage that fixes this issue.

If you're using Rails, just keep the "config.gem 'spatial_adapter'" in your environment.  The adapter for your database (and no others) will be loaded.

In general Ruby use, you need to explicitly request an adapter, such as:

require 'spatial_adapter/postgresql'

Feel free to grab the latest gem or install directly from Github as a Rails plugin.  I tested it here both ways, but let me know if there are outstanding issues.
