### ISSUE TITLE
type cast with JRuby

### ISSUE THREAD

**Issue by heroygt** [pdeffendol/spatial_adapter#11]
I am using PostgreSQL(jdbc adapter) and JRuby. The problem is when I load data from DB, the type cast doesn't work.  So I only got a string like "010100002....".

**Comment by pdeffendol** [comment]
spatial_adapter does not currently support the "jdbcpostgresql" ActiveRecord adapter.  It will only be enabled when using the "postgresql" adapter and the "pg" or "postgres" gems.
