### ISSUE TITLE
Rails 3.0 compatiblity

### ISSUE THREAD

**Issue by virtualfunction** [pdeffendol/spatial_adapter#12]
The should be fairly self-explanatory. I'm looking to move some projects to Rails 3.0 code base and I guess others are. The ActiveRecord internals have changed significantly since 2.3.

**Comment by pdeffendol** [comment]
The current version of spatial_adapter passes all tests with ActiveRecord 3.0.0 beta.  Perhaps you are referring to an older version with the find_by_\* modifications?  Those have been removed due to ActiveRecord version dependencies, and definitely would have needed an overhaul for 3.0.

**Comment by virtualfunction** [comment]
I've just updated using 

rails plugin install git://github.com/fragility/spatial_adapter.git 

and still get the error:

Column type `geometry` is not currently handled

I'm using Rails 3.0.0 trunk (which is close to the beta2 package released last week)

**Comment by virtualfunction** [comment]
I've just tried to make a new project by doing:

rails geo
cd geo
rails plugin install git://github.com/fragility/spatial_adapter.git

edit my config/database.yml as needed

and put in 

class BaseLineSystem < ActiveRecord::Migration
  def self.up

```
with_options :force => true do |database|
  database.create_table :dummies do |table|
    table.datetime    :created_at, :updated_at
    table.string      :name
    table.column      :position, :point
  end
end
```

  end

  def self.down
    tables.each do |name|
      drop_table name
    end
  end

  def self.tables
    connection.tables - [ 'schema_migrations', 'geometry_columns', 'spatial_ref_sys' ]
  end
end

for my first migration.

both: rails console, and rake db:migrate 

give me:

/activerecord/lib/active_record/base.rb:1141:in `method_missing': undefined local variable or method`establish_connection' for ActiveRecord::Base:Class (NameError)

This seems to stem from the require on the first line of:

vendor/plugins/spatial_adapter/lib/spatial_adapter/schema_definitions.rb

**Comment by virtualfunction** [comment]
Sorry, formatting seems to have messed up, you should get the idea though :)

Thanks for the quick reply earlier.

**Comment by pdeffendol** [comment]
Thanks for the detailed input.  Did you try using it as a gem instead of a plugin?

I'm pretty swamped with a project this week, but I'll try to take a look at it soon.

**Comment by virtualfunction** [comment]
Nope, just as a plugin. I'll switch to a gem.

I faffed about on my end and ran the rspec tests on my end. As you say they seem to pass OK (I found some failed as I was on PostGIS 1.4, but have updated since).

Will let you know the results in a bit.

Cheers
Jase.

**Comment by virtualfunction** [comment]
OK, Finally switched to gem, using:

gem 'spatial_adapter', :git => 'git://github.com/fragility/spatial_adapter.git'

In my Gemfile

still seem to have the same issue. My migrations and stuff seemed to work somewhat OK, however I found the root of the cause for me seems to be when I use AREL with tables that have geometry types, such as my User model.

Just doing: 

User.where :disabled => false
or even...
User.where

Even though disabled is not a geometry column seems trigger the error. I'm guessing AREL is scanning the column data types upon model load up and trying to work out how they map to native Ruby types, and this is where things are tripping up. 

If you don't seem to be able to replicate this on your end, leave me another shout and I'll make a ZIP up a minimal test/sample Rails project for you.

Thanks, J.

**Comment by achirkunov** [comment]
Pete,
I can confirm the problem Jason has. I have replicated a minimal test/sample Rails project as well.
The reason why your specs are fine is because you require ActiveRecord 2.3.5 in spec_helper. Specs fail with ActiveRecord3.0.0.beta3 because of issues with Arel.
I've forked spatial_adapter and made it Rails3 compatible.
Cheers
Anton

**Comment by pdeffendol** [comment]
Something must have changed recently in ActiveRecord 3 (go figure) because the specs were passing at around the beta1 time.  With beta3, there are a number of failures as you report.

**Comment by pdeffendol** [comment]
Just a note - this issue is mentioned in https://rails.lighthouseapp.com/projects/8994/tickets/4270-arel-032-broke-non-standard-column-types

**Comment by achirkunov** [comment]
Thanks for the answer. As Ernie mentioned in the ticket, the types that Arel handles are the only one that should ever show up based on a call to Column#type because of the simplified_types call in Column.initialize.

They resolved the issue by making the postgres adapter return standard column types for smallint and UUID. As Arel won't get fixed, spatial_adapter probably needs to go along and return a standard column type (e.g. string) as well.

**Comment by pdeffendol** [comment]
I just pushed the 1.1.0 gem.  All specs are passing with ActiveRecord 3.0.0 beta 3.  Thanks for the help and keep me informed if something else breaks.

**Comment by virtualfunction** [comment]
Horray :-)
Will get the update in sec. Many thanks everyone

**Comment by virtualfunction** [comment]
Hrm, had a play last night, seem to have found some other issue(s).

Tests seem to run fine (I made sure it was loading Rails 3.x instead of 2.3.5), however when using a dummy rails project I found the following:

firstly, I needed to explicitly call:
require 'spatial_adapter/postgresql'

I had setup the project to use spatial_adapter as a gem and thus defined gem 'spatial_adapter' in my Gemfile for bundler, so the above require shouldn't have been needed.

Further more, I'm not sure if this is an intentional change or not, but my migration was set to:

with_options :force => true do |database|
  database.create_table :dummies do |table|
    table.datetime    :created_at, :updated_at
    table.string      :name
    table.point       :position
  end
end

Which defines the position type to be point fine in the DB, however, it doesn't let me do something like: 

Dummy.create :name => 'Test', :position => Point.from_x_y(1, 2)

If I run the above, assuming I've called require 'spatial_adapter/postgresql' it will give me something like:

PGError: ERROR:  invalid input syntax for type point: "0101000020FFFFFFFF000000000000F03F0000000000000040"
LINE 1: ...") VALUES ('2010-04-22 11:00:15.588166', E'Test', E'01010000...

If I don't put the require in, none of the spatial AR hooks are active, so it just tries to serialize the Point data type as YAML.

After digging into the source a little, I see the postgresql.rb file's columns method only activates spatial column types of the column type is set to geography or geometry, so the point column type gets ignored by the spatial adapter hooks and seen as a plain string data-type by Rails.

Obviously, if I change the column type form Point to Geometry, inserting the Point.from_x_y(1,2) seems to work fine.

**Comment by pdeffendol** [comment]
Thanks, I'll try and get to it, but it might be a few days.  Apparently the "old" way of initializing plugins (with rails/init.rb) is no longer valid?

Is there a way to get a test case for your second observation?

**Comment by virtualfunction** [comment]
Hrm, just got back home, so justing my Desktop PC, and doing a fresh install of all things edge related and don't seem to replicate the 'point' issue on that, so I'm guessing I've got a barfed install somewhere on my laptop (Have a feeling it could be because I setup the GIS stuff on my test DB under PostGIS 1.4, but later uninstalled and rebuilt PostGIS 1.5 and forgot to run the update SQL script).

As far as require 'spatial_adapter/postgresql', Yes, I think Rails 3.0 has changed the plugin architecture a bit. Least it's easy to work around the issue for now with an explicit require. :-)

**Comment by pdeffendol** [comment]
I've added a Railtie to spatial_adapter as of version 1.1.1.  This should fix the Rails 3 compatibility when installed as a gem, and automatically load the adapter for your current database configuration.  Rails 2.3.x compatibility is maintained with the rails/init.rb method.

Please confirm - I tried it here successfully with Rails 3 beta 3.

**Comment by virtualfunction** [comment]
Sorry, not been checking here for the last week as I've had other distractions. Will have a look later. If I have any issue, rest assured I'll be back ;-) Thanks once again
