### ISSUE TITLE
remove_column in migrations

### ISSUE THREAD

**Issue by tashian** [pdeffendol/spatial_adapter#13]
I'm getting this:

undefined method `spatial?' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x104c284e0>
in .../gems/spatial_adapter-1.1.0/lib/spatial_adapter/postgresql.rb:102:in`remove_column'

when I try to remove a column in a migration under spatial_adapter 1.1.1:

remove_column :people, :website_one

Specifically, I was running rake db:migrate:redo at the time.

I also get this error under spatial_adapter 1.1.0.
Under spatial_adapter 1.0.0, the migration runs fine.

This is on Rails 2.3.5 with PostgreSQL & PostGIS 1.5.0, and GeoRuby 1.3.4.

Is there any additional info I can send along to help diagnose or fix this?

**Comment by pdeffendol** [comment]
Thanks for the information.  I added a new test to the Rspec to catch this error, and it's now fixed in version 1.1.2.

**Comment by tashian** [comment]
Wow, that was fast. Thanks!
