### ISSUE TITLE
Aggregate queries?

### ISSUE THREAD

**Issue by tashian** [pdeffendol/spatial_adapter#14]
A hello and a question. I'm using spatial_adapter in http://github.com/opengovernment/opengovernment/
It's been super helpful for us -- so thank you!

One thing I'd love to be able to do is an aggregate spatial query like this:

District.all(:select => "state_id, st_extent(geom) as geo", :group => :state_id)

Or even use find_by_sql.
But is there any way to get a spatial_adapter object back?
Right now I'm just getting raw text, eg:

> > District.all(:select => "state_id, st_extent(geom) as geo", :group => :state_id).first.geo
> > => "BOX(-106.645646 25.837377,-93.5164072637683 36.500704)"

Maybe I'm not casting correctly in my query?

**Comment by sabman** [comment]
as you know st_extent is a PostGIS. When you say spatial_adapter object do you mean a GeoRuby SimpleFeatures object?

**Comment by tashian** [comment]
Yes, I do mean a GeoRuby object. My assumption though, is that spatial_adapter, if anyone, should be responsible for magically creating a GeoRuby object and returning it in this case. Is that right?

**Comment by pdeffendol** [comment]
Someone may correct me here, but my experience is that any time you SELECT columns (or expressions in your case) that aren't part of that table's set of columns, then ActiveRecord just loads them in as strings.  I don't think this is a spatial_adapter issue.

You can easily verify by doing a different :select that includes an expression that returns a float, such as st_length.  Is the resulting ActiveRecord object attribute a string or a float?

**Comment by tashian** [comment]
Ahh -- that's an interesting behavior, I wonder what the rationale is. I've always thought find_by_sql was a bit weird because it returns objects "disguised" as ActiveRecord objects but with whatever arbitrary attributes you asked for in the select.

Anyway, sounds like spatial_adapter is doing the "right" thing in terms of conventions. And to solve my problem I just dealt with the string I was getting back. So we can close this if you think there's no issue here.
