### ISSUE TITLE
Compatibility with mysql2 driver

### ISSUE THREAD

**Issue by skrat** [pdeffendol/spatial_adapter#16]
I think this should be fairly simple to implement, I'm just hitting some nil.downcase on line 171 in mysql_spatial_adapter.rb

**Comment by pdeffendol** [comment]
See my comment on issue #18.  I am not going to add any more variations into the current incarnation of spatial_adapter due to the dependency management issues.

**Comment by nickurban** [comment]
Skrat, if you've managed to get mysql2 working, please let me know. I'm dealing with places with unicode names, and the old mysql driver has problems with unicode (at least with Rails 3). I'd really like unicode and spatial data to work at the same time :)

**Comment by cwise** [comment]
I've made modifications to get this working. I've never contributed before to a Git project (I work with Git all the time otherwise). Can someone direct me to a good guide on the steps involved in how I submit my proposed modifications?

**Comment by nickurban** [comment]
I'm new to GitHub myself, but as I understand it, the standard procedure is to fork the repository (http://help.github.com/forking/) and then send a pull request to the maintainer of the repository that you forked, asking them to merge in your changes (http://help.github.com/pull-requests/)

**Comment by cwise** [comment]
Thanks Nick. I submitted the request.

**Comment by pdeffendol** [comment]
Added in version 1.2.0
