### ISSUE TITLE
Unable to add index on MySQL InnoDB

### ISSUE THREAD

**Issue by jannuskool** [pdeffendol/spatial_adapter#22]
in first migration I do:

  def self.up
    create_table :locations, :force => true do |t|
      t.string :name
      t.text :description
      t.string :link
      t.point :geom, :null => false

```
  t.timestamps
end
```

and in one after that:

add_index :locations, :geom, :spatial => true

which doesn't succeed and shows error:

Mysql2::Error: The used table type doesn't support SPATIAL indexes: CREATE SPATIAL INDEX index_locations_on_geom ON locations (geom)

Using Rails 3.0.3, MySQL (Ver 14.14 Distrib 5.1.39, for apple-darwin10.0.0 (i386)), InnoDB. Shouldn't InnoDB support indexes? Can't figure what I'm doing wrong.  Any ideas? Do have GeoRuby and spatial_adapter in gemfile.

Thanks in advance.

Jan

**Comment by pdeffendol** [comment]
From the MySQL manual (http://dev.mysql.com/doc/refman/5.0/en/innodb-restrictions.html):

"InnoDB tables do not support spatial data types before MySQL 5.0.16. As of 5.0.16, InnoDB supports spatial data types, but not indexes on them."

**Comment by jannuskool** [comment]
I must have slipped that part. Thanks.
