### ISSUE TITLE
as_kml can produce google maps unreadable coordinates

### ISSUE THREAD

**Issue by boesemar** [pdeffendol/spatial_adapter#25]
..if lan or lon are saved out of the +180.0 and -180.0 degrees boundaries.

I patched it like this:

class GeoRuby::SimpleFeatures::Geometry
 alias :old_as_kml :as_kml

 # fixing google_earth not displaying coordinates properly if out of
 # -180 <> 180
 def as_kml
   old_as_kml.gsub(/[-+]?[0-9]_.?[0-9]_/) do |s| 
      next '' if s.empty?
      f = s.to_f
      next (f - 360.0).to_s if  f > 180.0
      next (f + 360.0).to_s if f < -180.0 
      f.to_s
   end
 end
end

**Comment by pdeffendol** [comment]
Some issues:
- Yes, the KML specification states that <coordinates> values are clamped to -180/180 for longitude and -90/90 for latitude.  If GeoRuby wants to honor the spec, then it should do something about non-conforming data.
- spatial_adapter is not specific to storage of lat/long data.  Monkey-patching GeoRuby doesn't seem like a good fit - if you're using lat/long, ensure that your data is within the limits in your validations.
- Your solution doesn't account for the -90/90 limit for latitude and therefore still can output invalid KML.

This is a good reference for those using KML output, but I'm not going to incorporate this patch as-is.
