### ISSUE TITLE
1.3.0 causes invalid mysql ddl type string instead of varchar on Ruby 1.8.7

### ISSUE THREAD

**Issue by jconley** [pdeffendol/spatial_adapter#28]
Using a clean rails 3.0.10 app with mysql 5.0.90
Add to Gemfile:
gem 'mysql', '2.8.1'
gem 'spatial_adapter', '1.3.0'

When spatial_adapter 1.3.0 is present:
rake db:migrate
SQL (0.2ms)  CREATE TABLE `schema_migrations` (`version` string NOT NULL) ENGINE=InnoDB
Mysql::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'string NOT NULL) ENGINE=InnoDB' at line 1: CREATE TABLE `schema_migrations` (`version` string NOT NULL) ENGINE=InnoDB

If you comment out spatial_adapter in Gemfile, this is generated instead.
rake db:migrate
SQL (48.3ms)  CREATE TABLE `schema_migrations` (`version` varchar(255) NOT NULL) ENGINE=InnoDB

**Comment by pdeffendol** [comment]
Does this happen with spatial_adapter version 1.2.0?

**Comment by jconley** [comment]
Works fine with 1.2.0

**Comment by pdeffendol** [comment]
I can't seem to reproduce this problem.  The only difference here is that I am using MySQL 5.5.15.

Have you tried using the mysql2 adapter?  (Change your Gemfile and database.yml to use "mysql2".)

**Comment by pdeffendol** [comment]
I installed MySQL 5.0.90 and I still cannot reproduce this.  You may need to send me an archive of the clean Rails app that produces the problem.

**Comment by jconley** [comment]
I just tested with rails 3.0.10 and mysql2 gem 0.2.13. same result, generates the same invalid sql.
can you capture what sql is generated in your development.log when you run db:migrate on an empty schema?  perhaps mysql 5.5 responds to the "string" type (although I dont see that documented)

**Comment by pdeffendol** [comment]
I ran rake db:migrate using the clean Rails app you sent me.  Same result.  Here is the log contents:

```
  SQL (0.9ms)  SHOW TABLES
  SQL (24.5ms)  CREATE TABLE `schema_migrations` (`version` varchar(255) NOT NULL) ENGINE=InnoDB
  SQL (0.4ms)  SHOW KEYS FROM `schema_migrations`
  SQL (17.0ms)  CREATE UNIQUE INDEX `unique_schema_migrations` ON `schema_migrations` (`version`)
  SQL (0.3ms)  SHOW TABLES
  SQL (0.1ms)  SHOW TABLES
  SQL (0.1ms)  SHOW TABLES
  schema_migrations Columns (0.7ms)  SHOW FIELDS FROM `schema_migrations`
  SQL (0.2ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations`
  SQL (0.1ms)  SHOW TABLES
```

Some other information may be helpful -
1.  What OS platform are you using?
2.  What Ruby are you using (1.8.7, 1.9.2, etc.)

**Comment by jconley** [comment]
1. OSX Lion /w Brew and Redhat EL5
2. Ruby Enterprise Edition 1.8.7 2011.03

**Comment by pdeffendol** [comment]
Confirmed to occur using REE 1.8.7 on OS X Lion and MySQL 5.5 but not on Ruby 1.9.2

**Comment by pdeffendol** [comment]
I pushed out a commit (ca18be8) that fixes the issue for me.  Will you take a look and report your results?

**Comment by jconley** [comment]
Works here as well.

**Comment by pdeffendol** [comment]
Thanks for the help - the 1.3.1 gem contains the fix.
