### ISSUE TITLE
sanitize_sql_hash_for_conditions issue w/ join on 2.3.2

### ISSUE THREAD

**Issue by markshaw** [pdeffendol/spatial_adapter#3]
It looks like get_rails2_conditions (called here)
      #For Rails >= 2
      def self.sanitize_sql_hash_for_conditions(attrs)
        conditions = get_rails2_conditions(attrs)
        replace_bind_variables(conditions, expand_range_bind_variables(attrs.values))
      end
Doesn't fully replicate the 2.3.2 base.rb code in the case where value.is_a?(Hash)

Unfortunately I'm new to rails to haven't yet figured out what aspects are missing, but I get a bind error when doing a join even if the table has no spatial columns (and the error goes away if I comment out overriding sanitize_sql_hash_for_conditions in the spatial_adapter code).

Any help is appreciated.

**Comment by jdrowell** [comment]
I've had a similar issue with 2.3.3, the latest fix (from July?) works fine for me. Thanks for keeping this updated guys!

**Comment by pdeffendol** [comment]
Closing as the find_by_\* enhancement have been removed.  Will revisit if/when they're added back in, although it will likely be ActiveRecord 3.0 only.
