### ISSUE TITLE
support for rails 3.2.2

### ISSUE THREAD

**Issue by jdayo** [pdeffendol/spatial_adapter#34]
trying to do bundle:

Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    spatial_adapter (>= 0) java depends on
      activerecord (< 3.1.0, >= 2.2.2) java

```
rails (= 3.2.2) java depends on
  activerecord (3.2.2)
```

I guess just updating the gemspec should suffice, I've not encountered any issue when using it under rails 3.2

**Comment by pdeffendol** [comment]
Hi, there are several other Issues on here that report incompatibility with Rails 3.1 and Rails 3.2.  Some even have proposed solutions (pull requests).  However, none of the pull requests fix compatibility for both MySQL and PostgreSQL, and they will not be incorporated until that time.  I noticed you're using JRuby - I haven't tested there for Rails 3.1+ - if you could run the test suite using JRuby and report results, that would help.

**Comment by thomax** [comment]
Any news on this? It's getting increasingly difficult to keep all gems in a project happy when activerecord must be < 3.1.0.

**Comment by pdeffendol** [comment]
No news and no plans.  As stated on the spatial_adapter main page, this library is not being developed further.  Use RGeo (https://github.com/dazuma/rgeo) instead, it works great with 3.2
