### ISSUE TITLE
Unit testing with rspec

### ISSUE THREAD

**Issue by JeffWaltzer** [pdeffendol/spatial_adapter#4]
I'm trying to get my code using PostGIS and this plugin under unit test using rspec

I'm having trouble getting tables with spatial columns loaded in the test db with the rake db:test:load rake task.  

rake db:schema:dump is giving me this

```
create_table "room_geometries", :force => true do |t|
  t.column "room_id", :integer
  t.column "created_at", :timestamp
  t.column "updated_at", :timestamp
  t.column "the_geom", :multi_polygon
end
```

DB Test load is giving me all the columns except for 'the_geom'.  

Is there instructions out there on what I need to do to get this testable?  (I've not seen much with the google searches I've done)

**Comment by pdeffendol** [comment]
I suspect that your test database isn't being initialized with the PostGIS functionality.  Keep in mind that the test db is recreated when you run your tests.  In our projects, we use a template database that contains the PostGIS functions, and indicate its usage in database.yml.  

Scan through your test.log after running rake db:test:load to see if there are any errors.

**Comment by pdeffendol** [comment]
The wiki (http://wiki.github.com/fragility/spatial_adapter/rails-and-postgis) contains some instructions for setting up a template database to ensure that your test database builds correctly.
