### ISSUE TITLE
PostGIS adapter not handling :null option properly

### ISSUE THREAD

**Issue by chewi** [pdeffendol/spatial_adapter#6]
The PostGIS adapter is currently initialising the column with super(base, name, type, limit, default, null). It should actually be super(base, name, type, limit, nil, nil, default, null) because the fifth and sixth arguments are actually for :precision and :scale. Consequently the :null option is not getting handled properly. I'm guessing this was due to a change in Rails? I'm using the 2-3-stable branch.

**Comment by pdeffendol** [comment]
I'll check on it as soon as I get some time.  It wouldn't surprise me if Rails changed the parameters at some point.

**Comment by pdeffendol** [comment]
If you get a chance, try it with the latest release (0.2.0) - if it still doesn't work I'll write up some rspec to reproduce the problem.

**Comment by chewi** [comment]
This aspect of it seems okay but it's broken in another way. It's picking up all my table indexes twice! On a table with one unique index across two columns, the old SELECT code still returned two rows but somehow ended up with just one index from it. The new SELECT code also returns two rows but ends up with two indexes.

**Comment by pdeffendol** [comment]
Thanks - I've fixed the duplicate index problem.  I left out a DISTINCT in the SQL.  Version 0.2.1 of the gem has the fix.

**Comment by chewi** [comment]
Thanks, that's done the trick. :)

**Comment by chewi** [comment]
It looks like the original issue was never actually fixed. I must admit, I'm slightly confused as I've only come to notice it now and I thought it was fixed before. I've tried to trace the offending line back through the history, which is difficult, because things have moved around a lot but I don't think it ever changed. Making the same change I suggested above still fixes the problem.

**Comment by chewi** [comment]
Once you've done this, you should probably also adjust the schema dump to check whether :limit is nil, otherwise you get :limit => nil appearing on every spatial column.

**Comment by pdeffendol** [comment]
That's interesting.  I thought it was fixed as well.  I'll go take a look, but my time is limited at the moment, so it might be a few days.
