### ISSUE TITLE
Conflict with redhillonrails_core schema dumper

### ISSUE THREAD

**Issue by chewi** [pdeffendol/spatial_adapter#7]
The redhillonrails_core plugin uses alias_method_chain to add foreign key indexes to the schema dump. However, these methods fail to get called when spatial_adapter is also installed. I haven't worked out the exact reason but the problem can be avoided if you make sure spatial_adapter is loaded first. One way to do this is to rename it to 0_spatial_adapter.

**Comment by pdeffendol** [comment]
You can set your plugin load order in environment.rb:

config.plugins = [:spatial_adapter, :all]

The :all symbol will specify all plugins not explicitly named
